import { Exo_2,Poppins } from "next/font/google";
import "./globals.css";
import { IntroContainer } from "@/components/custom/sub-intro/intro-container";
import { MainContainer } from "@/components/custom/main/main-container";
import WarpContainer from "@/components/custom/layout/warp-container"
const poppins = Poppins({
  weight: ["100","200","400", "500", "600", "700"],
  variable: "--font-poppins",
  subsets: ["latin"],
});
const exo2 = Exo_2({
  weight: ["100","200","400", "500", "600", "700"],
  variable: "--font-exo2",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <WarpContainer>
        <body
          className={`${exo2.className} antialiased fixed h-svh w-full flex justify-center`}
        >
            <section className="flex gap-2 justify-center mt-[5svh] max-w-[1400] w-full">
              <IntroContainer />
              <MainContainer>
                {children}
              </MainContainer>
            </section>
        </body>
      </WarpContainer>
    </html>
  );
}
